const employees = [
  {
    id: 1,
    email: "a@a.com",
    password: "123",
    firstName: "Shreshth",
    tasks: [
      {
        active: true,
        new_task: false,
        completed: false,
        failed: false,
        task_title: "Submit monthly report",
        task_description: "Complete and submit the monthly financial report.",
        task_date: "2025-07-05",
        task_category: "Finance",
      },
      {
        active: false,
        new_task: false,
        completed: true,
        failed: false,
        task_title: "Team meeting",
        task_description: "Participate in the weekly team sync-up.",
        task_date: "2025-07-01",
        task_category: "Meetings",
      },
      {
        active: true,
        new_task: false,
        completed: false,
        failed: false,
        task_title: "Client proposal draft",
        task_description: "Draft proposal for new client acquisition.",
        task_date: "2025-07-08",
        task_category: "Sales",
      },
    ],
    TaskCount: {
      newTasks: 0,
      completedTasks: 1,
      acceptedTasks: 2,
      failedTasks: 0,
    },
  },
  {
    id: 2,
    email: "jane.smith@example.com",
    password: "123",
    firstName: "Jane",
    tasks: [
      {
        active: false,
        new_task: false,
        completed: false,
        failed: true,
        task_title: "Update CRM data",
        task_description: "Clean and update contact information in CRM.",
        task_date: "2025-06-30",
        task_category: "Operations",
      },
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "Design email campaign",
        task_description: "Create layout for marketing email blast.",
        task_date: "2025-07-08",
        task_category: "Marketing",
      },
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "Internal training",
        task_description: "Attend internal skills development session.",
        task_date: "2025-07-10",
        task_category: "Training",
      },
      {
        active: false,
        new_task: false,
        completed: true,
        failed: false,
        task_title: "Review analytics",
        task_description: "Analyze recent campaign performance.",
        task_date: "2025-07-03",
        task_category: "Analytics",
      },
    ],
    TaskCount: {
      newTasks: 2,
      completedTasks: 1,
      acceptedTasks: 2,
      failedTasks: 1,
    },
  },
  {
    id: 3,
    email: "michael.brown@example.com",
    password: "123",
    firstName: "Michael",
    tasks: [
      {
        active: false,
        new_task: false,
        completed: true,
        failed: false,
        task_title: "Organize event",
        task_description: "Plan logistics for the product launch event.",
        task_date: "2025-06-28",
        task_category: "Events",
      },
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "Prepare budget estimate",
        task_description: "Estimate costs for upcoming quarter.",
        task_date: "2025-07-09",
        task_category: "Finance",
      },
      {
        active: false,
        new_task: false,
        completed: false,
        failed: true,
        task_title: "Client feedback review",
        task_description: "Review and document client feedback.",
        task_date: "2025-07-02",
        task_category: "Customer Support",
      },
      {
        active: true,
        new_task: false,
        completed: false,
        failed: false,
        task_title: "Website QA",
        task_description: "Run quality checks on new website deployment.",
        task_date: "2025-07-08",
        task_category: "QA",
      },
      {
        active: false,
        new_task: false,
        completed: true,
        failed: false,
        task_title: "Weekly sync",
        task_description: "Join cross-functional weekly alignment call.",
        task_date: "2025-07-04",
        task_category: "Meetings",
      },
    ],
    TaskCount: {
      newTasks: 1,
      completedTasks: 2,
      acceptedTasks: 2,
      failedTasks: 1,
    },
  },
  {
    id: 4,
    email: "emily.jones@example.com",
    password: "123",
    firstName: "Emily",
    tasks: [
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "Code review",
        task_description: "Review code submissions from junior developers.",
        task_date: "2025-07-08",
        task_category: "Development",
      },
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "Sprint planning",
        task_description: "Participate in planning for sprint 18.",
        task_date: "2025-07-07",
        task_category: "Agile",
      },
      {
        active: false,
        new_task: false,
        completed: true,
        failed: false,
        task_title: "Deploy patch",
        task_description: "Deploy hotfix for security vulnerability.",
        task_date: "2025-07-06",
        task_category: "Security",
      },
    ],
    TaskCount: {
      newTasks: 2,
      completedTasks: 1,
      acceptedTasks: 2,
      failedTasks: 0,
    },
  },
  {
    id: 5,
    email: "daniel.wilson@example.com",
    password: "123",
    firstName: "Daniel",
    tasks: [
      {
        active: false,
        new_task: false,
        completed: true,
        failed: false,
        task_title: "Product demo",
        task_description: "Conduct demo for prospective clients.",
        task_date: "2025-07-01",
        task_category: "Sales",
      },
      {
        active: false,
        new_task: false,
        completed: false,
        failed: true,
        task_title: "Fix server issue",
        task_description: "Resolve downtime on backend server.",
        task_date: "2025-07-03",
        task_category: "IT",
      },
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "Write documentation",
        task_description: "Document the new API endpoints.",
        task_date: "2025-07-08",
        task_category: "Documentation",
      },
      {
        active: true,
        new_task: true,
        completed: false,
        failed: false,
        task_title: "Team retrospective",
        task_description: "Discuss last sprint outcomes and improvements.",
        task_date: "2025-07-09",
        task_category: "Agile",
      },
      {
        active: false,
        new_task: false,
        completed: true,
        failed: false,
        task_title: "Security audit",
        task_description: "Assist with external audit preparations.",
        task_date: "2025-07-05",
        task_category: "Security",
      },
    ],
    TaskCount: {
      newTasks: 2,
      completedTasks: 2,
      acceptedTasks: 2,
      failedTasks: 1,
    },
  },
];


const admin = [{
  id: 100,
  firstName: "Admin",
  email: "admin@example.com",
  password: "123",
}];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
